apiVersion: v1
kind: Pod
metadata:
  name: redis-connection-test
  namespace: test
spec:
  template:
    spec:
      containers:
      - name: redis-cli
        image: redis:7.2-alpine
        command: ["sh", "-c"]
        args:
          - |
            echo "Running 10 Redis PING tests...";
            for i in $(seq 1 10); do
              echo "Attempt $i:"
              redis-cli -u redis://<user>:<password>@<host> ping
              sleep 2
            done
      restartPolicy: Never
      #nodeSelector:
        #kubernetes.io/os: linux
        #kubernetes.io/arch: amd64
  backoffLimit: 0
